name: Scan Start
on:  
  workflow_dispatch: 

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run NeuraLegion Scan
        uses: NeuraLegion/run-scan@v1
        with:
          api_token: ${{ secrets.ISAH_BRIGHTTOKEN }}
          hostname: app.brightsec.com
          name: Isah Bright Scan - ${{ github.sha }}
          restart_scan: aYyfuozNC5FEJUxta6Q57L
